### ISSUE TITLE
error during data featurize.py? 

### ISSUE THREAD

**Issue by SeekPoint** [baidu-research/GloballyNormalizedReader#2]
I had glove.840B.300d.txt unzip from glove.840B.300d.zip, is this right?

python3 featurize.py --datadir data --outdir featurized  --glove-path ../glove.840B.300d.txt 
Using TensorFlow backend.
Constructing vocabularies...
Finished...
Building word embedding matrix...
Traceback (most recent call last):
  File "featurize.py", line 317, in <module>
    preprocess()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "featurize.py", line 273, in preprocess
    vocab.construct_embedding_matrix(glove_path)
  File "/Users/GloballyNormalizedReader/vocab.py", line 85, in construct_embedding_matrix
    missing_word_value=lambda: 0.0)
  File "/Users/GloballyNormalizedReader/vocab.py", line 219, in load_word_vectors
    word2vec = FastWord2vec.get(path)
  File "/Users/GloballyNormalizedReader/vocab.py", line 202, in get
    WORD2VEC = FastWord2vec(path)
  File "/Users/GloballyNormalizedReader/vocab.py", line 141, in __init__
    binary=True)
  File "/usr/local/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 207, in load_word2vec_format
    vocab_size, vector_size = map(int, header.split())  # throws for invalid file format
ValueError: invalid literal for int() with base 10: ','

**Comment by SeekPoint** [comment]
mldl@mldlUB1604:~/ub16_prj/GloballyNormalizedReader$ python3 featurize.py --datadir data --outdir featurized  --glove-path ../DrQA/glove.840B.300d.zip 
Using TensorFlow backend.

Constructing vocabularies...
Finished...
Building word embedding matrix...
Traceback (most recent call last):
  File "featurize.py", line 317, in <module>
    preprocess()
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "featurize.py", line 273, in preprocess
    vocab.construct_embedding_matrix(glove_path)
  File "/home/mldl/ub16_prj/GloballyNormalizedReader/vocab.py", line 85, in construct_embedding_matrix
    missing_word_value=lambda: 0.0)
  File "/home/mldl/ub16_prj/GloballyNormalizedReader/vocab.py", line 219, in load_word_vectors
    word2vec = FastWord2vec.get(path)
  File "/home/mldl/ub16_prj/GloballyNormalizedReader/vocab.py", line 202, in get
    WORD2VEC = FastWord2vec(path)
  File "/home/mldl/ub16_prj/GloballyNormalizedReader/vocab.py", line 141, in __init__
    binary=True)
  File "/usr/local/lib/python3.5/dist-packages/gensim/models/keyedvectors.py", line 206, in load_word2vec_format
    header = utils.to_unicode(fin.readline(), encoding=encoding)
  File "/usr/local/lib/python3.5/dist-packages/gensim/utils.py", line 240, in any2unicode
    return unicode(text, encoding, errors=errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 11: invalid start byte
mldl@mldlUB1604:~/ub16_prj/GloballyNormalizedReader$ 
mldl@mldlUB1604:~/ub16_prj/GloballyNormalizedReader$

**Comment by JonathanRaiman** [comment]
@loveJasmine I think this might be because the embedding file from glove might still be zipped (I decompressed it a few months back, so I'd have to check this again to verify).
In the meantime my current sense is that this should work:
```
unzip ../DrQA/glove.840B.300d.zip
# creates unzipped ../DrQA/glove.840B.300d, which now is compatible with:
python3 featurize.py --datadir data --outdir featurized --glove-path ../DrQA/glove.840B.300d
```
Please let me know If it doesn't, I'd be happy to update the readme with steps to fix this! :)

**Comment by SeekPoint** [comment]
word2vec = gensim.models.KeyedVectors.load_word2vec_format(
                path,
                binary=True)   #so, this means it should be a bin file instead of *.txt

however, I change  binary=False with glove.840B.300d.txt, but it raise error yet, also report the file format issue

**Comment by SeekPoint** [comment]
ali-186590cc37a5:DrQA $ md5 glove.840B.300d.zip 
MD5 (glove.840B.300d.zip) = 2ffafcc9f9ae46fc8c95f32372976137
ali-186590cc37a5:DrQA $ md5 glove.840B.300d.txt 
MD5 (glove.840B.300d.txt) = eec7d467bccfa914726b51aac484d43a


would you share you md5 value of  glove.840B.300d.zip and glove.840B.300d.txt

**Comment by loveJasmine** [comment]
ali-186590cc37a5:GloballyNormalizedReader yike.ke$ md5 ../DrQA/glove.840B.300d.txt 
MD5 (../DrQA/glove.840B.300d.txt) = eec7d467bccfa914726b51aac484d43a

**Comment by SeekPoint** [comment]
it is a bug.

we shouldn't use load_word2vec_format to load a glove format file.
at least, we shoudd convert glove to word2vec format before load it by load_word2vec_format

please refer https://radimrehurek.com/gensim/scripts/glove2word2vec.html
